#!/bin/bash

echo "Hello!"
echo "It's shell script created for help you use npm without install on your PC"

uid=$(id -u $USER)
gid=$(id -g $USER)

echo "Run as $uid:$gid"

SCRIPTPATH=$(dirname $(realpath $0))

tty="-i"
if [ -t 1 ]; then
tty="-it"
fi

docker run --rm -v $SCRIPTPATH:"/app" -w "/app" -p 9080:8080 --user=$uid:$gid $tty node:latest npm "$@"
